[project]
name = "formacion-comit-lomas-del-sol"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "jupyterlab",
    "ipympl",
    "ipywidgets",
    "python-dotenv",
    "pyyaml",
]

[dependency-groups]
dev = [
    "pylint",
    "pytest",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
